language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"
  - "3.15"
  - "pypy3"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install -U pytest coverage pytest-cov
# command to run tests
script:
  - python3 -m pytest --cov=simpletree3 .
